"""empty message

Revision ID: 314ab8575f15
Revises: 3cb00c8f8d89
Create Date: 2025-07-10 13:21:21.915714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314ab8575f15'
down_revision = '3cb00c8f8d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_1'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
